# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-monitoring-service-rel-1-0-0
  namespace: processor
  labels:
    app: transaction-monitoring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-monitoring-service
  template:
    metadata:
      name: transaction-monitoring-service-rel-1-0-0
      labels:
        app: transaction-monitoring-service
      annotations:
        prometheus.io.scrape: 'false'
    spec:
      containers:
        - name: transaction-monitoring-service-rel-1-0-0
          image: docker.io/batzorig825/transaction-monitoring-service-rel-1-0-0-dev:1.0.0
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
          resources: {}
          imagePullPolicy: Always
        - name: tms-sidecar-rel-1-0-0
          image: docker.io/batzorig825/sidecar-rel-1-0-0:1.0.0
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
          resources: {}
          envFrom:
            - configMapRef:
                name: tz-configmap
          env:
            - name: FUNCTION_NAME
              value: "transaction-monitoring-service"
            - name: MAX_CPU
              value: "1"
            - name: PRODUCER_STREAM
              value: "event-director"
            - name: CONSUMER_STREAM
              value: ""
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: frmpullsecret
      schedulerName: default-scheduler
      enableServiceLinks: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
