# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: typology-processor-rel-1-0-0
  namespace: processor
  labels:
    app: typology-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typology-processor
  template:
    metadata:
      name: typology-processor-rel-1-0-0
      labels:
        app: typology-processor
      annotations:
        prometheus.io.scrape: 'false'
    spec:
      containers:
        - name: typology-processor-rel-1-0-0
          image: docker.io/batzorig825/typology-processor-rel-1-0-0-dev:1.0.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          envFrom:
            - configMapRef:
                name: tz-configmap
          env:
            - name: FUNCTION_NAME
              value: "typology-processor"
            - name: INTERDICTION_PRODUCER
              value: "interdiction-service"
            - name: PRODUCER_STREAM
              value: "interdiction-service"
            - name: CONSUMER_STREAM
              value: "interdiction-service"
            - name: MAX_CPU
              value: "1"
          imagePullPolicy: Always
        - name: tp-sidecar-rel-1-0-0
          image: docker.io/batzorig825/sidecar-rel-1-0-0:1.0.0
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
          resources: {}
          env:
            - name: NATS_SERVER
              value: "nats.development.svc.cluster.local:4222"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: frmpullsecret
      schedulerName: default-scheduler
      enableServiceLinks: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
