apiVersion: v1
kind: ConfigMap
metadata:
  name: tz-ppa-configmap
  namespace: processor
data:
  FUNCTION_NAME: "batch-ppa"
  NODE_ENV: "production"
  MAX_CPU: "1"

  # Batch-PPA
  TMS_ENDPOINT: "http://168.138.184.62:5000"
  QUOTING: "false"
  PORT: "3000"
  MAX_FILE_SIZE: "100" #mb
  DELIMITER: "|"

  # REDIS
  REDIS_DATABASE: "0"
  REDIS_AUTH: "exampleAuth"
  REDIS_SERVERS: '[{"host":"168.138.184.62", "port":16379}]'
  REDIS_IS_CLUSTER: "false"
  DISTRIBUTED_CACHETTL: "300"
  DISTRIBUTED_CACHE_ENABLED: "true"

  # ArangoDB
  PSEUDONYMS_DATABASE: "pseudonyms"
  PSEUDONYMS_DATABASE_URL: "tcp://arango.development.svc.cluster.local:8529"
  PSEUDONYMS_DATABASE_USER: "root"
  PSEUDONYMS_DATABASE_PASSWORD: "Passw0rdDB2#25"
  PSEUDONYMS_DATABASE_CERT_PATH: ""

  TRANSACTION_HISTORY_DATABASE: "transactionHistory"
  TRANSACTION_HISTORY_DATABASE_URL: "tcp://arango.development.svc.cluster.local:8529"
  TRANSACTION_HISTORY_DATABASE_USER: "root"
  TRANSACTION_HISTORY_DATABASE_PASSWORD: "Passw0rdDB2#25"
  TRANSACTION_HISTORY_DATABASE_CERT_PATH: ""

  # ELASTIC APM
  APM_ACTIVE: "false"
  APM_SERVICE_NAME: "batch-ppa"
  APM_URL: "http://apm:8200"
  APM_SECRET_TOKEN: ""

  # LOGGING
  LOGSTASH_HOST: "logstashhost"
  LOGSTASH_PORT: "8080"
  LOGSTASH_LEVEL: "info"