# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: batch-ppa-rel-1-0-0
  namespace: processor
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      nodePort: 30001
  selector:
    app: batch-ppa
  type: NodePort
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster