apiVersion: v1
kind: ConfigMap
metadata:
  name: tz-service-configmap
  namespace: processor
data:
  APP_NAME: "Service"
  KC_URL: "http://168.138.184.62:30980"
  KC_REALM: "fraudblok"
  KC_CLIENTID: "internal"
  KC_SECRET: "tgP6dVh9ZI92Mfiu03XXbBa9ssbxlrZB"
  DB_URL: "http://arango.development.svc.cluster.local:8529"
  DB_USER: "root"
  DB_PASSWORD: "Passw0rdDB2#25"
  DB_TRANSACTION_NAME: "evaluationResults"
  DB_TRANSACTION_HIST_NAME: "transactionHistory"
  DB_CONFIG_NAME: "configuration"
  DB_PSEUDONYMS_NAME: "pseudonyms"
  DB_REPORT_NAME: "report"
  DB_LOG_NAME: "webappLogs"
  ELASTICSEARCH_NODE: "http://elastic:PasSw0rd2o25@168.138.184.62:9200"