# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: tz-service
  namespace: processor
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      nodePort: 30000
  selector:
    app: tz-service
  type: NodePort
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster