# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-aggregation-decisioning-processor-rel-1-0-0
  namespace: processor
  labels:
    app: transaction-aggregation-decisioning-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-aggregation-decisioning-processor
  template:
    metadata:
      name: transaction-aggregation-decisioning-processor-rel-1-0-0
      labels:
        app: transaction-aggregation-decisioning-processor
      annotations:
        prometheus.io.scrape: 'false'
    spec:
      containers:
        - name: transaction-aggregation-decisioning-processor-rel-1-0-0
          image: batzorig825/tz-tadp:dev
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          envFrom:
            - configMapRef:
                name: tz-configmap
          env:
            - name: FUNCTION_NAME
              value: "transaction-aggregation-decisioning-processor"
            - name: PRODUCER_STREAM
              value: "cms"
            - name: SUPPRESS_ALERTS
              value: "true"
            - name: MAX_CPU
              value: "1"
          imagePullPolicy: Always
        - name: tadp-sidecar-rel-1-0-0
          image: docker.io/batzorig825/sidecar-rel-1-0-0:1.0.0
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
          resources: {}
          env:
            - name: NATS_SERVER
              value: "nats.development.svc.cluster.local:4222"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: frmpullsecret
      schedulerName: default-scheduler
      enableServiceLinks: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
